### ISSUE TITLE
facewarp.exe

### ISSUE THREAD

**Issue by efthymisgeo** [adobe-research/MakeItTalk#7]
Hello,
I'm trying to execute a part of `main_end2end_cartoon.py` script.
Specifically, I am interested in the facewarp part of the script so what i actually do is
`facewarp/facewarp.exe examples_cartoon/wilk.png out/triangulation.txt out/reference_points.txt out/warped_points.txt -novsync -dump`  
but i get the following error.

```
EXCEPTION:
        Failed to read image '-novsync'.
``` 

When i omit both ```-novsync``` and ```-dump``` arguments the script seems to run but does not output something. 

Am I missing something or is it a bug?
Thanks, Tim

**Comment by yzhou359** [comment]
@efthymisgeo Thanks for pointing this out. The demo script has been updated in my fork, latest commit.
The problem here is because the facewarp.exe needs to take another input argument `background_image` before the last `-novsync` or `-dump`. The right command is

`facewarp/facewarp.exe examples_cartoon/wilk.png out/triangulation.txt out/reference_points.txt out/warped_points.txt examples_cartoon/wilk_bg.jpg -novsync -dump`

Make sure the relative path is correct and the background image exists. You can check the demo in my fork for a quick try. https://github.com/yzhou359/MakeItTalk/blob/5ba9815532ef818c1ef0ba92b03d098964e70074/main_end2end_cartoon.py#L205

**Comment by efthymisgeo** [comment]
Hey @yzhou359  thanks a lot for your answer!
I also came across an alternative for Unix-based systems in an older [commit](https://github.com/adobe-research/MakeItTalk/blob/f2eaeea0e24fcb363569376c8c3ce4a1aaee79ad/main_end2end_cartoon.py#L290) of this repo. One needs to install wine in order to execute it properly.
